version: '3.7'
services:
  base:
    image: ghostfolio-base:latest
    volumes:
      - ghostfolio-data:/ghostfolio
      - .env:/ghostfolio/.env:ro
    env_file: .env

  client:
    image: ghostfolio-base:latest
    volumes:
      - ghostfolio-data:/ghostfolio
      - .env:/ghostfolio/.env:ro
    env_file: .env
    command: "/scripts/start-client.sh"
    restart: unless-stopped
    depends_on:
      - "server"
    ports:
      - 4200:4200

  server:
    image: ghostfolio-base:latest
    volumes:
      - ghostfolio-data:/ghostfolio
      - .env:/ghostfolio/.env:ro
    env_file: .env
    command: "/scripts/start-server.sh"
    restart: unless-stopped
    depends_on:
      - "postgres"
      - "redis"

  postgres:
    image: postgres:12
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: 'redis:alpine'
    restart: unless-stopped
    volumes:
      - redis-data:/data

volumes:
  ghostfolio-data:
  postgres-data:
  redis-data:
